### ISSUE TITLE
[文章推荐] - Developing iOS 8 Apps Using Swift

### ISSUE THREAD

**Issue by sivagao** [ipader/SwiftGuide#1]
这个教程大概7篇blog，一步步讲解了一个『itunes music search app』的制作
对于async http, api delegate, 异步图片，动画，代码分层，interface builder都做了清晰的介绍。

http://jamesonquave.com/blog/

http://jamesonquave.com/blog/developing-ios-8-apps-using-swift-animations-audio-and-custom-table-view-cells/

**Comment by mrmign** [comment]
赞
