### ISSUE TITLE
在线"Swift中文指南"的"基础部分-隐式解析可选类型"的源代码举例没有更新

### ISSUE THREAD

**Issue by jiongge** [ipader/SwiftGuide#11]
在线"Swift中文指南"的"基础部分-隐式解析可选类型"的源代码举例
if assumedString {
    println(assumedString)
}
// 输出 "An implicitly unwrapped optional string."

http://numbbbbb.gitbooks.io/-the-swift-programming-language-/content/chapter2/01_The_Basics.html

应该是
if assumedString != nil {
    println(assumedString)
}
// prints "An implicitly unwrapped optional string."
https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID309

**Comment by ipader** [comment]
请递交到以下项目组。谢谢。
https://github.com/numbbbbb/the-swift-programming-language-in-chinese
