### ISSUE TITLE
RatingBar评分控件

### ISSUE THREAD

**Issue by saiwu-bigkoo** [ipader/SwiftGuide#17]
https://github.com/saiwu-bigkoo/iOS-RatingBar

跟Android的RatingBar一样有两种模式，评分模式和只读模式
支持视图编辑，自定义星星数量，评分等级
另外还能支持非整数星，0.5颗星，0.1颗星
可以开启动画效果

![](https://github.com/saiwu-bigkoo/iOS-RatingBar/blob/master/preview/ratingbardemo.gif)

**Comment by ipader** [comment]
分享 @SwiftLanguage
