### ISSUE TITLE
请问The Swift Programming Language会出版麽

### ISSUE THREAD

**Issue by xuzhen2014** [ipader/SwiftGuide#18]
最近在学习Swift，很高兴能看到这么好的资源，为你们团队点赞!

顺带问一下这个会出版吗？

**Comment by ipader** [comment]
你误会了，那是 [@梁杰_numbbbbb](http://weibo.com/u/5042408187) 翻译团队干的。

通常，官网文档翻译不会正式出版，除非苹果有意授权。
