### ISSUE TITLE
Guide 提问

### ISSUE THREAD

**Issue by aiqiuqiu** [ipader/SwiftGuide#25]
问下啊  这篇Guide 的Readme.md 是不是在周报里有多   Readme  太长了  要是周报都有  我就按照周报去看了

**Comment by aiqiuqiu** [comment]
顺便 弱弱的推荐下 自己写的Swift 小Project   https://github.com/aiqiuqiu/Tuan  顺便捞个Star

**Comment by ipader** [comment]
建议直接看：[Swift 文章精选](https://github.com/ipader/SwiftGuide/blob/master/Featured-Articles.md)，[Swift 项目精选](https://github.com/ipader/SwiftGuide/blob/master/Featured.md) 以及周报。
你的项目可以微博分享，我帮你转发。

**Comment by aiqiuqiu** [comment]
http://m.weibo.cn/3048827033/3896418533913665/qq?wm=3333_2001&from=1054593010&sourcetype=qq   麻烦转发一下
