### ISSUE TITLE
优秀文章推荐

### ISSUE THREAD

**Issue by 649395594** [ipader/SwiftGuide#29]
你好，最近在翻译objc的[《Advanced Swift》](https://www.objc.io/books/advanced-swift/)，中文版在[Advanced Swift中文版](http://www.jianshu.com/p/18744b078508)。翻译进度和质量都有保障，如果感觉不错的话欢迎收藏。

**Comment by ipader** [comment]
已经微博推荐，下期会收录。多谢。

**Comment by ipader** [comment]
分享后出现预期的版权提醒，因此，抱歉已经删除了。

@onevcat 回复：
“objc中国正在和objc.io谈翻译授权的问题，然后我们会在一月atSwift的会上见个面确定这件事情。毕竟人家的书是商业作品，版权保护，所以我觉得这么做并不妥。当然如果也联系过授权的话另说（objc中国会在之后确定后有偿招募翻译者，所以这位同学完全可以不用着急先等一个月）”
