### ISSUE TITLE
Android dev 现在在学习swift

### ISSUE THREAD

**Issue by ostea** [ipader/SwiftGuide#38]
目前已经掌握swift的基本语法，之前没有过oc的开发基础。 一直在做Android ，想对自己做个突破，想问下，有什么好的上手项目可以推荐下嘛~？ :P ,3Q

**Comment by survivingME** [comment]
个人觉得应该继续加强swift，如果语法基础好的话考虑考虑跟别人合作接个私活吧，有安卓基础的话应该不难上手

**Comment by medisean** [comment]
先把swift基础学好很重要，推荐《The Swift Programming Language》和《Thinking, Fast and Slow》

**Comment by ostea** [comment]
@medisean @survivingME 
: P，3Q  目前已经在和项目组里的一位iOS同学用Swift重构一个项目，目前市面上的书籍还是推荐用官方文档吧，版本还不是很稳定，看官方给出的版本改动消息感觉还是蛮大的。   《Thinking, Fast and Slow》 大学的时候阅读过一些，好吧  回去翻箱倒柜看看~ :+1:

**Comment by ipader** [comment]
推荐 《Swift 学习指引》 http://swiftguide.cn/  开发者的第一份 Swift 语言中文学习指南。
